version: '3'
services:
  elasticsearch:
    container_name: elasticsearch_app
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
    environment: 
      discovery.type: single-node
    networks:
      - kibana_elasticsearch  

networks:
  kibana_elasticsearch:
    driver: bridge